name: My first workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome message
        run: echo "my first github actions work"
      
      - name: list files
        run: ls

      - name: read files
        run: cat README.md
