name: Generate ASCII Artwork

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v5
        
      - name: Install cowsay
        run: sudo apt-get install cowsay -y

      - name: Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover,I am a Dragon....RAWR">> dragon.txt
      
      - name: Test file exists
        run: grep-i "dragon" dragon.txt

      - name: read file
        run: cat dragon.txt

      - name: checkout repository file
        run: ls -ltra

           


    #   - name: welcome message
    #     run: echo "my first github actions work"
      
    #   - name: list files
    #     run: ls

    #   - name: read files
    #     run: cat README.md
