name: Generate ASCII Artwork - Multiple jobs

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay
        run: sudo apt-get install cowsay -y

      - name: Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt

    #   - name: Upload artifact
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: dragon-file
    #       path: dragon.txt

  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon-file

      - name: Test file exists
        run: grep -i "dragon" dragon.txt

  third_job:
    runs-on: ubuntu-latest
    needs: [second_job]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon-file

      - name: read file
        run: cat dragon.txt

